language: node_js
node_js:
  - "node"
before_install:
  - yarn add react react-dom
script:
  - yarn run prod
  - yarn run build-color
  - yarn run copy
  - yarn run lint
  - yarn run test
branches:
only:
  - master
yarn: true
