'use strict';

export default [
  '# GoogleDrive',
  'Use to login `google drive` and get data from `google drive api`. You need to add `https://apis.google.com/js/api.js` to html.',
  '',
  '#### Props',
  '- `client_id(required)`: You can see [here](https://developers.google.com/drive/v3/web/quickstart/js) to find your `client_id`.',
  '- `updateSigninStatus(required)`: This will be called when status of auth is checked.',
  '- `children(required)`',
  '- `authClick`: If `isSignedIn` is false, `onClick` of children will be this function.',
  '- `signoutClick`: If `isSignedIn` is true, `onClick` of children will be this function.',
  '',
  '#### Example',
  '```js',
  '\'use strict\';',
  '',
  'import React from \'react\';',
  'import GoogleDrive from \'cat-components/lib/GoogleDrive\';',
  '',
  'export default class Example extends React.Component {',
  '  constructor(props) {',
  '    super(props);',
  '    this.state = {',
  '      isSignedIn: false,',
  '    }',
  '',
  '    this.updateSigninStatus = this.updateSigninStatus.bind(this);',
  '  }',
  '',
  '  render() {',
  '    const {isSignedIn, info} = this.state;',
  '',
  '    return (',
  '      <GoogleDrive clientId=\'test\'',
  '                   updateSigninStatus={this.updateSigninStatus}',
  '      >',
  '        <button>{isSignedIn ? \'Sign out\' : \'Authorize\' }</button>',
  '      </GoogleDrive>',
  '    );',
  '  }',
  '',
  '  updateSigninStatus(isSignedIn) {',
  '    if(isSignedIn)',
  '      \\*Do all things here.*\\',
  '',
  '    this.setState({isSignedIn});',
  '  }',
  '}',
  '```'
];
