'use strict';

export default [
  '# GoTo',
  'Use to scroll main `DOM` to target `DOM` or top of window.',
  '',
  '#### Props',
  '- `children(required)`',
  '- `main(required)`: This is main `DOM` which is controlled.',
  '- `target`: Main `DOM` will scroll to target `DOM`. If this is not set, main `DOM` will scroll to top of window.',
  '- `sec`: This is duration of animation.',
  '- `fps`: This is fps of animation.',
  '- `animation`: This is function of animation. It can be a name of [eases](https://www.npmjs.com/package/eases) or a function.',
  '',
  '`main` and `target` will be a string. This component uses those string with `document.querySelector` to get `DOM`.',
  '',
  '#### Example',
  '```js',
  '\'use strict\';',
  '',
  'import React from \'react\';',
  'import GoTo from \'cat-components/lib/GoTo\';',
  '',
  'export default class Example extends React.Component {',
  '  render() {',
  '    return (',
  '      <GoTo main=\'body\'>',
  '        <button>Go To</button>',
  '      </GoTo>',
  '    );',
  '  }',
  '}',
  '```'
];
