'use strict';

export default [
  '# [Language](./#Language)',
  'Use to choose language. You can use `import chooseLanguage from \'cat-components/lib/utils/chooseLanguage\';`. You can use like `chooseLanguage(\'eng\')({eng: \'English\', chi: \'中文\'})`.',
  '',
  '#### Props',
  '- `language(default: \'eng\')`: The language is choosen.',
  '',
  '#### Example',
  '```js',
  '\'use strict\';',
  '',
  'import React from \'react\';',
  'import PropTypes from \'prop-types\';',
  'import Language from \'cat-components/lib/Language\';',
  '',
  'class Example extends React.Component {',
  '  static contextTypes = {',
  '    chooseLanguage: PropTypes.func.isRequired',
  '  }',
  '',
  '  render() {',
  '    const {chooseLanguage} = this.context;',
  '',
  '    return (',
  '      <div>',
  '        {chooseLanguage({',
  '          chi: \'中文\',',
  '          eng: \'English\'',
  '        })}',
  '      </div>',
  '    );',
  '  }',
  '}',
  '',
  'export default () => (',
  '  <Language>',
  '    <Example />',
  '  </Language>',
  ');',
  '```'
];
