'use strict';

export default [
  '# [Menu](./#Menu)',
  'Use to make a menu.',
  '',
  '#### Props',
  '- `children(required)`',
  '- `menu(required)`: This is a component of `menu`.',
  '- `menuStyle`: This is the `style` of `menu` parentNode.',
  '- `showStyle`: This is the animation of showing `menu`.',
  '- `hideStyle`: This is the animation of hiding `menu`.',
  '- `delay`: This is the delay time of hiding `menu`.',
  '',
  '#### Example',
  '```js',
  '\'use strict\';',
  '',
  'import React from \'react\';',
  'import Menu from \'cat-components/lib/Menu\';',
  '',
  'export default class Example extends React.Component {',
  '  render() {',
  '    return (',
  '      <Menu menu={<h4>Menu</h4>}>',
  '        <button>menu</button>',
  '      </Menu>',
  '    );',
  '  }',
  '}',
  '```'
];
