'use strict';

export default [
  '# [Toggle](./#Toggle)',
  'Use to make a Toggle. You can use `radio` and `checkbox`.',
  '',
  '#### Other packages',
  '- [react-icons](https://gorangajic.github.io/react-icons/fa.html)',
  '',
  '#### Props',
  '- `checked`: Use to set default clicked.',
  '- `icon`: You can use this to change icon when component is not clicked.',
  '- `clickedIcon`: You can use this to change icon when component is clicked.',
  '- `type(default: checkbox)`: Use to choose type of the component. You can use `radio` and `checkbox`. If you use `radio`, you should add `clicked` to `props` in order that the value of the component will be only one value.',
  '',
  '#### Example',
  '```js',
  '\'use strict\';',
  '',
  'import React from \'react\';',
  'import Toggle from \'cat-components/lib/Toggle\';',
  '',
  'export default class Example extends React.Component {',
  '  constructor(props) {',
  '    super(props);',
  '    this.state = {',
  '      value: \'1\'',
  '    }',
  '',
  '    this.click = this.click.bind(this);',
  '  }',
  '',
  '  render() {',
  '    return (',
  '      <div>',
  '        <Toggle type=\'radio\'',
  '                clicked={value === \'1\'}',
  '                onClick={this.click(\'1\')}',
  '        />',
  '        <Toggle type=\'radio\'',
  '                clicked={value === \'2\'}',
  '                onClick={this.click(\'2\')}',
  '        />',
  '      </div>',
  '    );',
  '  }',
  '',
  '  click(value) {',
  '    return isClicked => {',
  '      if(isClicked)',
  '        this.setState({value});',
  '      else',
  '        this.setState({value: \'\'});',
  '    }',
  '  }',
  '}',
  '```'
];
